# Generated by Django 3.2.21 on 2023-09-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryshop', '0002_auto_20230917_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='groceryshop.category'),
        ),
    ]
