# Generated by Django 3.2.21 on 2023-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryshop', '0007_alter_savedcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcart',
            name='items',
            field=models.ManyToManyField(related_name='saved_carts', to='groceryshop.Food'),
        ),
    ]
