# Generated by Django 3.2.21 on 2023-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryshop', '0008_alter_savedcart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
