# Generated by Django 3.2.21 on 2023-10-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryshop', '0009_auto_20231009_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='groceryshop.Food'),
        ),
    ]
